apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: zipkin-server
  name: zipkin-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: zipkin-server
    spec:
      containers:
      - image: openzipkin/zipkin
        imagePullPolicy: Always
        name: zipkin
      restartPolicy: Always
  
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: zipkin-server
  name: zipkin-server
  namespace: default
spec:
  ports:
  - port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    app: zipkin-server
  sessionAffinity: None
  type: LoadBalancer

