apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-03-31T16:30:19Z"
  generation: 1
  labels:
    app: manage-currency-conversion
  name: manage-currency-conversion
  namespace: default
  resourceVersion: "709"
  uid: 9a1e85af-916f-43b2-8fb9-4aadb3336a9e
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: manage-currency-conversion
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: manage-currency-conversion
    spec:
      containers:
      - image: deancha12/manage-currency-conversion-kubernates:0.0.11-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: manage-currency-conversion-kubernates
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-03-31T16:30:20Z"
    lastUpdateTime: "2022-03-31T16:30:20Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-03-31T16:30:19Z"
    lastUpdateTime: "2022-03-31T16:30:20Z"
    message: ReplicaSet "manage-currency-conversion-75654bf6f9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
  
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-03-31T16:30:27Z"
  labels:
    app: manage-currency-conversion
  name: manage-currency-conversion
  namespace: default
  resourceVersion: "723"
  uid: 60e67873-9e0e-48e2-8d41-ca1dde073db0
spec:
  clusterIP: 10.96.35.143
  clusterIPs:
  - 10.96.35.143
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30548
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: manage-currency-conversion
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: localhost

