apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: manage-currency-conversion
  name: manage-currency-conversion
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manage-currency-conversion
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: manage-currency-conversion
    spec:
      containers:
      - image: deancha12/manage-currency-conversion-kubernates:0.0.11-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: manage-currency-conversion-kubernates
      restartPolicy: Always
  
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: manage-currency-conversion
  name: manage-currency-conversion
  namespace: default
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: manage-currency-conversion
  sessionAffinity: None
  type: LoadBalancer


