apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: convert-currency
  name: convert-currency
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: convert-currency
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: convert-currency
    spec:
      containers:
      - image: deancha12/convert-currency-service-kubernates:0.0.11-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: convert-currency-service-kubernates
      restartPolicy: Always
 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: convert-currency
  name: convert-currency
  namespace: default
spec:
  ports:
  - port: 8100
    protocol: TCP
    targetPort: 8100
  selector:
    app: convert-currency
  sessionAffinity: None
  type: LoadBalancer
  
