# ... Deployment YAML definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: convert-currency-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: convert-currency-demo
  template:
    metadata:
      labels:
        app: convert-currency-demo
    spec:
      containers:
      - image: deancha12/convert-currency:1.0.1
        name: convert-currency
        env:
          - name: SPRING_ZIPKIN_BASE-URL
            value: http://zipkin-server-demo.default.svc.cluster.local:9411
        ports:
           - containerPort: 8081
---
# ... Service YAML definition
apiVersion: v1
kind: Service
metadata:
  name: convert-currency-demo
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: convert-currency-demo
  type: LoadBalancer  #CHECK THIS OUT
