# ... Deployment YAML definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-server-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin-server-demo
  template:
    metadata:
      labels:
        app: zipkin-server-demo
    spec:
      containers:
      - image: openzipkin/zipkin
        imagePullPolicy: IfNotPresent
        name: zipkin-server
---
# ... Service YAML definition
apiVersion: v1
kind: Service
metadata:
  name: zipkin-server-demo
spec:
  ports:
    - port: 9411
      protocol: TCP
      targetPort: 9411
  selector:
    app: zipkin-server-demo
  type: LoadBalancer
